### ISSUE TITLE
can not open D:/Projects/animal_calib/articulation/artist_config_sym.json

### ISSUE THREAD

**Issue by browningChen** [anl13/MAMMAL_core#1]
老师您好，我遇到了以下报错
![image](https://github.com/anl13/MAMMAL_core/assets/141602132/1ab41d12-7fb8-4e12-8f8d-1f6f6b25eeb0)
我已经按照要求修改了config_BamaPig3D_main.json.
但是还是不知道这里是因为哪里出现的问题

**Comment by browningChen** [comment]
```
线程 0x3080 已退出，返回值为 0 (0x0)。
线程 0x6cfc 已退出，返回值为 0 (0x0)。
“posesolver.exe”(Win32): 已加载“C:\Windows\System32\nvspcap64.dll”。无法查找或打开 PDB 文件。
“posesolver.exe”(Win32): 已加载“C:\Windows\System32\psapi.dll”。无法查找或打开 PDB 文件。
“posesolver.exe”(Win32): 已卸载“C:\Windows\System32\psapi.dll”
“posesolver.exe”(Win32): 已加载“C:\Windows\System32\psapi.dll”。无法查找或打开 PDB 文件。
“posesolver.exe”(Win32): 已卸载“C:\Windows\System32\psapi.dll”
“posesolver.exe”(Win32): 已加载“C:\Windows\System32\psapi.dll”。无法查找或打开 PDB 文件。
“posesolver.exe”(Win32): 已卸载“C:\Windows\System32\psapi.dll”
“posesolver.exe”(Win32): 已加载“C:\Windows\System32\psapi.dll”。无法查找或打开 PDB 文件。
“posesolver.exe”(Win32): 已卸载“C:\Windows\System32\psapi.dll”
“posesolver.exe”(Win32): 已加载“C:\Windows\System32\powrprof.dll”。无法查找或打开 PDB 文件。
“posesolver.exe”(Win32): 已加载“C:\Windows\System32\umpdc.dll”。无法查找或打开 PDB 文件。
“posesolver.exe”(Win32): 已加载“C:\Windows\System32\winsta.dll”。无法查找或打开 PDB 文件。
线程 0x6ee8 已退出，返回值为 -1 (0xffffffff)。
线程 0x1294 已退出，返回值为 -1 (0xffffffff)。
线程 0x713c 已退出，返回值为 -1 (0xffffffff)。
线程 0x33b8 已退出，返回值为 -1 (0xffffffff)。
线程 0x441c 已退出，返回值为 -1 (0xffffffff)。
线程 0x6fc0 已退出，返回值为 -1 (0xffffffff)。
线程 0x3cac 已退出，返回值为 -1 (0xffffffff)。
线程 0x1e58 已退出，返回值为 -1 (0xffffffff)。
线程 0x6fdc 已退出，返回值为 -1 (0xffffffff)。
线程 0x7430 已退出，返回值为 -1 (0xffffffff)。
线程 0x5f00 已退出，返回值为 -1 (0xffffffff)。
线程 0x6b2c 已退出，返回值为 -1 (0xffffffff)。
线程 0x5598 已退出，返回值为 -1 (0xffffffff)。
线程 0x7c50 已退出，返回值为 -1 (0xffffffff)。
线程 0x4880 已退出，返回值为 -1 (0xffffffff)。
线程 0x5a64 已退出，返回值为 -1 (0xffffffff)。
线程 0x6a94 已退出，返回值为 -1 (0xffffffff)。
线程 0x5fec 已退出，返回值为 -1 (0xffffffff)。
线程 0x4364 已退出，返回值为 -1 (0xffffffff)。
线程 0x640 已退出，返回值为 -1 (0xffffffff)。
线程 0x49dc 已退出，返回值为 -1 (0xffffffff)。
线程 0x70b0 已退出，返回值为 -1 (0xffffffff)。
线程 0x4370 已退出，返回值为 -1 (0xffffffff)。
线程 0x63a4 已退出，返回值为 -1 (0xffffffff)。
线程 0x4b48 已退出，返回值为 -1 (0xffffffff)。
线程 0x27f8 已退出，返回值为 -1 (0xffffffff)。
线程 0x1254 已退出，返回值为 -1 (0xffffffff)。
程序“[23852] posesolver.exe”已退出，返回值为 -1 (0xffffffff)。
```

**Comment by anl13** [comment]
Sorry about the bug. It is because the path was fixed. You should search for the path "D:/Projects/animal_calib/articulation/artist_config_sym.json" and replace it with your path "E:/MAMMAL_core/articulation/PIG_model.json". 

-----chinese version of the answer: -------
不好意思，看上去是路径配置的问题，可能我之前写死了一些路径没改过来。你搜索一下整个project，看看哪里有调用artist_model_sym.json这个文件，一律改成你现在的PIG_model.json的路径试试。

**Comment by anl13** [comment]
I will fix this bug in next commit.

**Comment by browningChen** [comment]
> Sorry about the bug. It is because the path was fixed. You should search for the path "D:/Projects/animal_calib/articulation/artist_config_sym.json" and replace it with your path "E:/MAMMAL_core/articulation/PIG_model.json".
> 
> -----chinese version of the answer: ------- 不好意思，看上去是路径配置的问题，可能我之前写死了一些路径没改过来。你搜索一下整个project，看看哪里有调用artist_model_sym.json这个文件，一律改成你现在的PIG_model.json的路径试试。

Thanks for ur reply，
I did search for the text 'artist_config_sym.json' in Visual Studio, but I wasn't able to fig it out. T_T
And I got another issue in
https://github.com/anl13/MAMMAL_core/blame/6404081040300311dfc7e3b9b77a169ff75ffe68/articulation/articulation.vcxproj#L138
```
<ClCompile Include="..\utils\volume.cpp" />
```
volume.cpp in folder "MAMAL_core\utils" doesn't exsist

**Comment by browningChen** [comment]
And "articulation/PIG_model.json" line2, "folder" must set to user_own_path before start Step3 in Doc/Demo.md like Step2 too

**Comment by anl13** [comment]
> And "articulation/PIG_model.json" line2, "folder" must set to user_own_path before start Step3 in Doc/Demo.md like Step2 too

yes, that's true.

**Comment by anl13** [comment]
> > Sorry about the bug. It is because the path was fixed. You should search for the path "D:/Projects/animal_calib/articulation/artist_config_sym.json" and replace it with your path "E:/MAMMAL_core/articulation/PIG_model.json".
> > -----chinese version of the answer: ------- 不好意思，看上去是路径配置的问题，可能我之前写死了一些路径没改过来。你搜索一下整个project，看看哪里有调用artist_model_sym.json这个文件，一律改成你现在的PIG_model.json的路径试试。
> 
> Thanks for ur reply， I did search for the text 'artist_config_sym.json' in Visual Studio, but I wasn't able to fig it out. T_T And I got another issue in https://github.com/anl13/MAMMAL_core/blame/6404081040300311dfc7e3b9b77a169ff75ffe68/articulation/articulation.vcxproj#L138
> 
> ```
> <ClCompile Include="..\utils\volume.cpp" />
> ```
> 
> volume.cpp in folder "MAMAL_core\utils" doesn't exsist

Simply delete "volume.cpp" where it appears may help. This file is useless.

**Comment by browningChen** [comment]
I finally done demo by copying folder `E:\MAMMAL_core\articulation` to `D:\Projects\animal_calib\articulation` and change the name of `PIG_model.json` to `artist_model_sym.json` 
Sorry about that we are bad at programming cause we are biologist, waiting to ur updates!
